version: '3.7'
services:
  database_mongo:
    image: mongo:6.0.5
    container_name: database_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authapi
      - MONGO_INITDB_ROOT_PASSWORD=0L01cNliRvelk0gGwRNfpZyU0ThuYVbwZXITJsBm
    volumes:
      - data:/data/db
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - auth_mongodb

volumes:
  data:

networks:
  auth_mongodb: